# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mvvm_10' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mvvm_10

pod 'ReactiveCocoa', '~> 2.0'



  target 'mvvm_10Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mvvm_10UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
